defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : visual_genome
    - experiment : debug

dataset_size: 200

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}